# Generated by Django 6.0.2 on 2026-02-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0002_consultancysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancysession',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
