# Generated by Django 6.0.2 on 2026-02-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('upi', 'UPI'), ('manual', 'Manual')], default='stripe', max_length=20),
        ),
    ]
