# Generated by Django 6.0.2 on 2026-02-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_videocall_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocall',
            name='audio_only',
            field=models.BooleanField(default=False),
        ),
    ]
